// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A Genkit flow for suggesting transaction categories (personal, business, mixed) based on transaction description and past transactions.
 *
 * - suggestTransactionCategory - A function that suggests a category for a given transaction.
 * - SuggestTransactionCategoryInput - The input type for the suggestTransactionCategory function.
 * - SuggestTransactionCategoryOutput - The return type for the suggestTransactionCategory function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTransactionCategoryInputSchema = z.object({
  description: z.string().describe('The description of the transaction.'),
  pastTransactions: z.array(
    z.object({
      description: z.string(),
      category: z.enum(['personal', 'business', 'mixed']),
    })
  ).optional().describe('Past transactions of the user, including description and category.'),
});
export type SuggestTransactionCategoryInput = z.infer<typeof SuggestTransactionCategoryInputSchema>;

const SuggestTransactionCategoryOutputSchema = z.object({
  category: z.enum(['personal', 'business', 'mixed']).describe('The suggested category for the transaction.'),
  reason: z.string().describe('The reason for the suggested category.'),
});
export type SuggestTransactionCategoryOutput = z.infer<typeof SuggestTransactionCategoryOutputSchema>;

export async function suggestTransactionCategory(input: SuggestTransactionCategoryInput): Promise<SuggestTransactionCategoryOutput> {
  return suggestTransactionCategoryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTransactionCategoryPrompt',
  input: {schema: SuggestTransactionCategoryInputSchema},
  output: {schema: SuggestTransactionCategoryOutputSchema},
  prompt: `Você é um assistente financeiro especialista em ajudar autônomos e pequenos empreendedores no Brasil a separar as contas.

Sua tarefa é analisar a descrição de uma transação e sugerir a categoria mais provável.

As regras para escolher a categoria são:
1.  **business (Empresarial):** Despesas claramente relacionadas ao trabalho.
    - Exemplos: "Assinatura Adobe", "Google Ads", "Aluguel Escritório", "Pagamento Fornecedor XYZ".
2.  **personal (Pessoal):** Despesas que não têm relação com o trabalho.
    - Exemplos: "Netflix", "iFood", "Cinema", "Farmácia Droga Raia".
3.  **mixed (Misto):** Despesas que beneficiam tanto a vida pessoal quanto o trabalho.
    - Exemplos: "Supermercado Atacadão", "Posto Ipiranga Gasolina", "Conta de Internet VIVO Fibra".

A transação para analisar é:
Descrição: {{{description}}}

O seu output DEVE SER um JSON. O campo 'category' no JSON deve ser OBRIGATORIAMENTE um dos três valores em inglês: 'personal', 'business', ou 'mixed'.
O campo 'reason' deve ser uma explicação curta e útil em português para o usuário.
`,
});

const suggestTransactionCategoryFlow = ai.defineFlow(
  {
    name: 'suggestTransactionCategoryFlow',
    inputSchema: SuggestTransactionCategoryInputSchema,
    outputSchema: SuggestTransactionCategoryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
